WIP

diff --git a/openqa-investigate b/openqa-investigate
--- a/openqa-investigate
+++ b/openqa-investigate
@@ -24,6 +24,10 @@ client_args=(api --header 'User-Agent: openqa-investigate (https://github.com/os
 jq_output_limit="${jq_output_limit:-15}"
 curl_args=(-L --user-agent "openqa-investigate")
 echoerr() { echo "$@" >&2; }
+lightbulb="💡"
+question="❓"
+monocle="🧐"
+investigate_help_link="$question[*Detailed explanation of this comment*](https://github.com/os-autoinst/scripts#More-details-and-examples-about-openqa-investigate-comments)"
 
 clone() {
     local origin id name_suffix refspec unsupported_cluster_jobs pending_cluster_jobs name base_prio clone_settings casedir repo out url clone_id
@@ -171,11 +175,11 @@ finalize_investigation_comment() {
         return 0
     fi
 
-    local comment="Automatic investigation jobs for job $id:
+    local comment="### Automatic investigation jobs for job $id:
 
 $comment_text
 
-💡[*Detailed explanation of this comment*](https://github.com/os-autoinst/scripts#More-details-and-examples-about-openqa-investigate-comments)"
+$investigate_help_link"
     "${client_call[@]}" -X PUT jobs/"$first_cluster_job_id"/comments/"$comment_id" text="$comment"
 
     # also write a comment on the job we're actually investigating
@@ -184,12 +188,16 @@ $comment_text
     fi
 }
 
-fetch-investigation-results() {
-    local origin_job_id=$1
-    local state job investigate_type other_id result investigate_comment output comment_lines
+fetch-investigate-comment() {
+    local job_id=$1
+    "${client_call[@]}" -X GET jobs/"$job_id"/comments | runjq -r '[.[] | select(.text | contains("Automatic investigation jobs for job") and contains(":investigate:retry**:"))] | min_by(.id)' || return $?
 
-    investigate_comment=$("${client_call[@]}" -X GET jobs/"$origin_job_id"/comments | runjq -r '[.[] | select(.text | contains("Automatic investigation jobs for job") and contains(":investigate:retry**:"))] | min_by(.id)') || return $?
-    [[ $investigate_comment == 'null' ]] && return
+}
+
+fetch-investigation-results() {
+    local origin_job_id=$1 investigate_comment=$2
+    local state job investigate_type other_id result output comment_lines
+
     output=$(echo "$investigate_comment" | runjq -r '.text') || return $?
     mapfile -t comment_lines <<<"$output"
 
@@ -215,12 +223,12 @@ is-ok() {
 identify-issue-type() {
     # Fetch job data for all 4 investigation jobs. If one is not yet finished,
     # return special 142 to retrigger this hook later again.
-    local origin_job_id=$1
+    local origin_job_id=$1 investigate_comment=${2:-""}
     local state result investigate_type passed output result_lines
     local pass_lgt='' pass_lgb='' pass_lgtb=''
     product_issue=false test_issue=false
 
-    output=$(fetch-investigation-results "$origin_job_id") || return $?
+    output=$(fetch-investigation-results "$origin_job_id" "$investigate_comment") || return $?
     mapfile -t result_lines <<<"$output"
 
     for line in "${result_lines[@]}"; do
@@ -245,7 +253,7 @@ identify-issue-type() {
 
 post-investigate() {
     local id=$1 retry_name=$2
-    local rc=0 status
+    local rc=0 status investigate_comment comment_text
     [[ ! "$retry_name" =~ investigate:retry$ ]] && echo "Job is ':investigate:' already, skipping investigation" && return 0
     # We are in the investigate:retry job now. From here we will check the
     # results of the other investigation jobs, if necessary
@@ -257,27 +265,39 @@ post-investigate() {
     # cluster jobs might have the same OPENQA_INVESTIGATE_ORIGIN as the root retry job
     [[ $retry_name != "$origin_name:investigate:retry" ]] && echo "Job $retry_name ($id) is not a retry of $origin_name ($origin_job_id)" && return 0
 
-    comment="Investigate retry job **$retry_name**: $host_url/t$id"
+    investigate_comment="$(fetch-investigate-comment "$origin_job_id")" || return $?
+    [[ $investigate_comment == 'null' ]] && return
+    comment_text=$(echo "$investigate_comment" | runjq -r '.text') || return $?
+    comment_text=$(echo "$comment_text" | grep -v "Detailed explanation")
+    comment_id=$(echo "$investigate_comment" | runjq -r '.id') || return $?
+    comment=$comment_text
+    comment+=---$'\n'"### $lightbulb Analysis"$'\n'$'\n'"Investigate retry job **$retry_name**: $host_url/t$id"
+    comment+=" $retry_result."
     if is-ok "$retry_result"; then
-        comment+=" $retry_result, likely a sporadic failure"
+        comment+=$'\n'"**Likely a sporadic failure**"
     else
-        comment+=" failed"
         local product_issue=false
         local test_issue=false
-        identify-issue-type "$origin_job_id" || return $?
+        identify-issue-type "$origin_job_id" "$investigate_comment"|| return $?
 
         if "$product_issue"; then
-            comment+="."$'\n'"Jobs including the last good build are ok, likely a product issue"
+            comment+=$'\n'$'\n'"Jobs including the last good build are ok. **Likely a product issue**"
         elif "$test_issue"; then
-            comment+="."$'\n'"Jobs including the last good test are ok, likely a test issue"
+            comment+=$'\n'$'\n'"Jobs including the last good test are ok. **Likely a test issue**"
         else
-            comment+=", likely not a sporadic failure"
+            comment+=$'\n'$'\n'"**Likely not a sporadic failure**"
         fi
     fi
+    comment+=$'\n'$'\n'"---"$'\n'$'\n'"$investigate_help_link"
 
+#    warn "================ Comment"
+#    warn "$comment"
+#    exit
     # meanwhile the original job might have been deleted already, handle
     # gracefully
-    out=$("${client_call[@]}" -X POST jobs/"$origin_job_id"/comments text="$comment" 2>&1) || rc=$?
+#    out=$("${client_call[@]}" -X POST jobs/"$origin_job_id"/comments text="$comment" 2>&1) || rc=$?
+    out=$("${client_call[@]}" -X PUT jobs/"$origin_job_id"/comments/"$comment_id" text="$comment" 2>&1) || rc=$?
+    warn "????????????????????????? $out"
     if [[ "$rc" -ne 0 ]]; then
         status=$(echo "$out" | runjq .error_status 2>/dev/null || echo "unknown")
         if [[ "$status" != "404" ]]; then
